"""
train.py
========
Fine-tune YOLOv8 on the combined COCO + custom-class dataset produced by
auto_label.py.

Key ideas
---------
* We START from a pretrained YOLOv8 checkpoint — this transfers all 80 COCO
  weights and only adds new heads for custom classes (transfer learning).
* Training is short (default 50 epochs) because the backbone is already trained.
* Results (weights + metrics) are saved to runs/train/<experiment>/

Usage
-----
python training/train.py --data data/labeled/dataset.yaml --classes "earphones" "earbuds"
python training/train.py --data data/labeled/dataset.yaml --model yolov8s --epochs 80 --batch 16
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

from ultralytics import YOLO


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class CustomTrainer:
    """
    Wraps Ultralytics YOLO training with sensible defaults for
    fine-tuning on a small custom dataset.

    Parameters
    ----------
    data_yaml   : Path to the dataset.yaml generated by auto_label.py
    model_name  : Base YOLOv8 variant (yolov8n, yolov8s, …)
    epochs      : Training epochs (50 is usually enough for fine-tuning)
    batch       : Batch size (-1 = auto)
    img_size    : Training image size in pixels
    device      : 'cpu', '0' (first GPU), 'mps' (Apple Silicon), or '' (auto)
    project     : Output root directory
    name        : Experiment sub-directory name
    """

    def __init__(
        self,
        data_yaml  : str | Path,
        model_name : str   = "yolov8n",
        epochs     : int   = 50,
        batch      : int   = -1,
        img_size   : int   = 640,
        device     : str   = "",
        project    : str   = "runs/train",
        name       : str   = "custom_yolo",
    ) -> None:
        self.data_yaml  = Path(data_yaml)
        self.model_name = model_name if model_name.endswith(".pt") else f"{model_name}.pt"
        self.epochs     = epochs
        self.batch      = batch
        self.img_size   = img_size
        self.device     = device
        self.project    = project
        self.name       = name

        if not self.data_yaml.is_file():
            raise FileNotFoundError(f"Dataset YAML not found: {self.data_yaml}\n"
                                    "Run auto_label.py first.")

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def train(self) -> Path:
        """
        Start training and return the path to the best weights file.
        """
        print("=" * 60)
        print("  YOLOv8 Custom Training")
        print("=" * 60)
        print(f"  Base model  : {self.model_name}")
        print(f"  Dataset     : {self.data_yaml}")
        print(f"  Epochs      : {self.epochs}")
        print(f"  Batch size  : {'auto' if self.batch == -1 else self.batch}")
        print(f"  Image size  : {self.img_size}px")
        print(f"  Device      : {'auto' if not self.device else self.device}")
        print("=" * 60)
        print()

        # Load base model (downloads if needed)
        model = YOLO(self.model_name)

        # ----------------------------------------------------------------
        # Augmentation strategy for small scraped datasets
        # ----------------------------------------------------------------
        augmentation_params = dict(
            hsv_h      = 0.015,   # hue jitter
            hsv_s      = 0.7,     # saturation jitter
            hsv_v      = 0.4,     # brightness jitter
            degrees    = 10.0,    # rotation
            translate  = 0.1,     # translation
            scale      = 0.5,     # zoom in/out
            shear      = 2.0,
            flipud     = 0.0,     # vertical flip (usually not for objects)
            fliplr     = 0.5,     # horizontal flip
            mosaic     = 1.0,     # mosaic augmentation (4 images combined)
            mixup      = 0.1,     # blend two images
            copy_paste = 0.1,     # copy-paste augmentation
        )

        # ----------------------------------------------------------------
        # Start training
        # ----------------------------------------------------------------
        results = model.train(
            data       = str(self.data_yaml),
            epochs     = self.epochs,
            batch      = self.batch,
            imgsz      = self.img_size,
            device     = self.device if self.device else None,
            project    = self.project,
            name       = self.name,
            # Optimiser
            optimizer  = "AdamW",
            lr0        = 0.001,
            lrf        = 0.01,
            momentum   = 0.937,
            weight_decay = 0.0005,
            warmup_epochs = 3,
            # Early stopping
            patience   = 20,
            # Augmentation
            **augmentation_params,
            # Misc
            save       = True,
            save_period = 10,   # save checkpoint every 10 epochs
            plots      = True,
            verbose    = True,
        )

        # Locate best weights
        best_weights = Path(self.project) / self.name / "weights" / "best.pt"
        if best_weights.is_file():
            print(f"\n[Train] ✓ Best weights saved → {best_weights}")
            self._print_next_steps(best_weights)
        else:
            print("\n[Train] Training complete. Check runs/train/ for weights.")

        return best_weights

    # ------------------------------------------------------------------

    @staticmethod
    def _print_next_steps(weights_path: Path) -> None:
        print()
        print("=" * 60)
        print("  Next steps")
        print("=" * 60)
        print(f"  1. Test your model on an image:")
        print(f"     python main.py --mode image --source photo.jpg \\")
        print(f"                    --model {weights_path}")
        print()
        print(f"  2. Use webcam with your new model:")
        print(f"     python main.py --model {weights_path}")
        print()
        print(f"  3. Evaluate on validation set:")
        print(f"     python training/evaluate.py --model {weights_path}")
        print("=" * 60)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="Fine-tune YOLOv8 on COCO + custom classes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Quick test run (CPU, nano model)
  python training/train.py --data data/labeled/dataset.yaml --epochs 20

  # Better accuracy (GPU recommended)
  python training/train.py --data data/labeled/dataset.yaml \\
      --model yolov8s --epochs 80 --batch 16 --device 0
        """,
    )
    p.add_argument("--data",    required=True,
                   help="Path to dataset.yaml (output of auto_label.py)")
    p.add_argument("--model",   default="yolov8n",
                   choices=["yolov8n","yolov8s","yolov8m","yolov8l","yolov8x"],
                   help="Base YOLOv8 variant. Larger = more accurate, slower to train.")
    p.add_argument("--epochs",  type=int,   default=50)
    p.add_argument("--batch",   type=int,   default=-1,
                   help="Batch size. -1 = auto (uses 60%% of GPU memory). (default: -1)")
    p.add_argument("--imgsz",   type=int,   default=640)
    p.add_argument("--device",  type=str,   default="",
                   help="Device: '' (auto), 'cpu', '0' (first GPU), 'mps' (Apple M-chip)")
    p.add_argument("--project", type=str,   default="runs/train")
    p.add_argument("--name",    type=str,   default="custom_yolo")
    args = p.parse_args()

    trainer = CustomTrainer(
        data_yaml  = args.data,
        model_name = args.model,
        epochs     = args.epochs,
        batch      = args.batch,
        img_size   = args.imgsz,
        device     = args.device,
        project    = args.project,
        name       = args.name,
    )
    trainer.train()


if __name__ == "__main__":
    main()